/**
 * Generated by `python tools/media.py` — do not edit by hand.
 *
 * Maps each original in `public/assets/img/` to the AVIF widths that exist
 * in `public/assets/opt/`, so `<Media>` can build a truthful srcset.
 */

export const mediaManifest: Record<string, readonly number[]> = {
  "/assets/img/copper-facade-bishkek.jpg": [
    400,
    800,
    1200,
    1800,
    2400,
    2752
  ],
  "/assets/img/copper-facade-canopy-structure.webp": [
    400,
    800,
    1200,
    1800,
    2400,
    2752
  ],
  "/assets/img/copper-facade-construction.jpg": [
    400,
    800,
    1200,
    1800,
    2400,
    2752
  ],
  "/assets/img/copper-facade-cutsheets.jpg": [
    400,
    800,
    1200,
    1800
  ],
  "/assets/img/copper-facade-marking.jpg": [
    400,
    800,
    1200,
    1800
  ],
  "/assets/img/copper-facade-nodes.png": [
    400,
    800,
    1200,
    1800,
    2400,
    3600
  ],
  "/assets/img/copper-facade-panel-fit-poster.jpg": [
    400,
    800,
    1200,
    1592
  ],
  "/assets/img/daylight-massing-card.webp": [
    400,
    720
  ],
  "/assets/img/daylight-massing.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/hero-bg.webp": [
    640
  ],
  "/assets/img/insolation-mound-card.webp": [
    400,
    720
  ],
  "/assets/img/insolation-mound-heatmap-nodes.png": [
    400,
    800,
    1200,
    1800,
    2400,
    2600
  ],
  "/assets/img/insolation-mound-heatmap.jpg": [
    400,
    800,
    1200,
    1800
  ],
  "/assets/img/insolation-mound-mound-nodes.png": [
    400,
    800,
    1200,
    1800,
    2400,
    2600
  ],
  "/assets/img/insolation-mound-rays.jpg": [
    400,
    800,
    1200,
    1800,
    2400,
    3840
  ],
  "/assets/img/insolation-mound-sunpath.jpg": [
    400,
    800,
    1200,
    1800,
    2400,
    2752
  ],
  "/assets/img/insolation-mound-voxels.jpg": [
    400,
    800,
    1200,
    1800,
    2400,
    3840
  ],
  "/assets/img/insolation-mound-windows-nodes.png": [
    400,
    800,
    1200,
    1800,
    2400,
    2600
  ],
  "/assets/img/jewelry-casting-risk-cluster-ring.png": [
    400,
    800,
    1200,
    1800,
    2400,
    3840
  ],
  "/assets/img/jewelry-casting-risk-cover-card.webp": [
    400,
    720
  ],
  "/assets/img/jewelry-casting-risk-cover.webp": [
    400,
    800,
    1200,
    1600
  ],
  "/assets/img/jewelry-casting-risk-hero.png": [
    400,
    800,
    1200,
    1800
  ],
  "/assets/img/jewelry-casting-risk-nodes.png": [
    400,
    800,
    1200,
    1724
  ],
  "/assets/img/jewelry-casting-risk-pendant.png": [
    400,
    800,
    1200,
    1800,
    2400,
    3840
  ],
  "/assets/img/jewelry-casting-risk-rejects.jpg": [
    400,
    800,
    1200,
    1800
  ],
  "/assets/img/jewelry-casting-risk-result.png": [
    400,
    800,
    1200,
    1800
  ],
  "/assets/img/jewelry-casting-risk-signet-ring.png": [
    400,
    800,
    1200,
    1800,
    2400,
    3840
  ],
  "/assets/img/jewelry-casting-risk-stone-ring.png": [
    400,
    800,
    1200,
    1800,
    2400,
    3840
  ],
  "/assets/img/jewelry-casting-risk-workflow.webp": [
    400,
    800,
    1200,
    1800
  ],
  "/assets/img/mcp-rhino-agent-card.webp": [
    400,
    720
  ],
  "/assets/img/mcp-rhino-agent-cover-poster.jpg": [
    400,
    800,
    1000
  ],
  "/assets/img/mcp-rhino-agent-d2-1.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/mcp-rhino-agent-d2-2.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/mcp-rhino-agent-d2-3.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/mcp-rhino-agent-d2-4.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/mcp-rhino-agent-d3-1.jpg": [
    400,
    800,
    1200,
    1400
  ],
  "/assets/img/mcp-rhino-agent-d3-2.jpg": [
    400,
    800,
    1200,
    1400
  ],
  "/assets/img/mcp-rhino-agent-d4-2.jpg": [
    400,
    800,
    1200,
    1400
  ],
  "/assets/img/mcp-rhino-agent-d5-1.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/mcp-rhino-agent-d5-2.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/mcp-rhino-agent-forms.jpg": [
    400,
    800,
    1200,
    1800
  ],
  "/assets/img/mcp-rhino-agent-geometry.jpg": [
    400,
    800,
    1200,
    1400
  ],
  "/assets/img/mcp-rhino-agent-hero-poster.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/mcp-rhino-agent-ov-1.png": [
    400,
    700
  ],
  "/assets/img/mcp-rhino-agent-ov-2.png": [
    400,
    700
  ],
  "/assets/img/mcp-rhino-agent-ov-3.png": [
    400,
    700
  ],
  "/assets/img/mcp-rhino-agent-ov-4.png": [
    400,
    700
  ],
  "/assets/img/mcp-rhino-agent-ov-5.png": [
    400,
    700
  ],
  "/assets/img/mcp-rhino-agent-ov-6.png": [
    400,
    700
  ],
  "/assets/img/mcp-rhino-agent-ref-absolute-world.jpg": [
    400,
    557
  ],
  "/assets/img/mcp-rhino-agent-ref-aqua-tower.jpg": [
    400,
    675
  ],
  "/assets/img/mcp-rhino-agent-ref-gherkin.jpg": [
    400,
    675
  ],
  "/assets/img/mcp-rhino-agent-ref-karlatornet.jpg": [
    400,
    771
  ],
  "/assets/img/mcp-rhino-agent-ref-shanghai-tower.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/mcp-rhino-agent-ref-turning-torso.jpg": [
    400,
    677
  ],
  "/assets/img/mcp-rhino-agent-workflow.png": [
    400,
    800,
    1200,
    1800,
    2400,
    2560
  ],
  "/assets/img/mcp-rhino-agent.jpg": [
    400,
    800,
    1200,
    1600
  ],
  "/assets/img/pedestrian-flow-card.webp": [
    400,
    720
  ],
  "/assets/img/pedestrian-flow-heatmap-poster.jpg": [
    400,
    800,
    1152
  ],
  "/assets/img/pedestrian-flow-home-poster.jpg": [
    400,
    720
  ],
  "/assets/img/pedestrian-flow-install-poster.jpg": [
    400,
    800,
    1152
  ],
  "/assets/img/pedestrian-flow-nodes.png": [
    400,
    800,
    1200,
    1800,
    2400,
    3600
  ],
  "/assets/img/pedestrian-flow-people-poster.jpg": [
    400,
    800,
    1152
  ],
  "/assets/img/pedestrian-flow-template-poster.jpg": [
    400,
    800,
    1152
  ],
  "/assets/img/pedestrian-flow-toolbar.png": [
    400,
    536
  ],
  "/assets/img/pedestrian-flow.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/portrait-600.webp": [
    400,
    600
  ],
  "/assets/img/portrait.png": [
    400,
    800,
    900
  ],
  "/assets/img/revit-panel-export-card.webp": [
    400,
    720
  ],
  "/assets/img/revit-panel-export.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/tessellation-studies-card.webp": [
    400,
    720
  ],
  "/assets/img/tessellation-studies.jpg": [
    400,
    800,
    900
  ],
  "/assets/img/voxel-architecture-card.jpg": [
    400,
    800,
    1200,
    1800,
    2400,
    2627
  ],
  "/assets/img/voxel-architecture-catalogue.jpg": [
    400,
    800,
    1200,
    1800,
    2400,
    2752
  ],
  "/assets/img/voxel-architecture-nodes.png": [
    400,
    800,
    1200,
    1800,
    2400,
    3575
  ],
  "/assets/img/wind-comfort-card.webp": [
    400,
    720
  ],
  "/assets/img/wind-comfort-demo-poster.jpg": [
    400,
    800
  ],
  "/assets/img/wind-comfort-nodes.png": [
    400,
    800,
    1200,
    1800,
    2400,
    3600
  ]
};
